name: Man10BankRobber
version: '${project.version}'
main: yusama125718.man10_bank_robber.Man10BankRobber
api-version: 1.17

commands:
  mbr:
  mbrop:

permissions:
  mbr.op:
    default: op
  mbr.start:
    default: op
  mbr.p:
    default: true

depend:
  - Vault